import propTypes from 'prop-types'

// eslint-disable-next-line camelcase
import { Instrument_Sans } from 'next/font/google'

import './globals.css'
import '#/node_modules/minireset.css/minireset.min.css'

import { Header, Footer } from './components/organisms/ui'

const InstrumentSans = Instrument_Sans({ subsets: ['latin'] })

export const metadata = {
  title: {
    template: '%s | Redu',
    title: 'Redu',
  },
  description: 'Generated by create next app',
  keywords: ['portfolio', 'developer', 'frontend'],
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={InstrumentSans.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}

RootLayout.propTypes = {
  children: propTypes.node,
}
